
<html>
<head>
<link rel ="stylesheet" type="text/css" href="new 3.css">
<style>
body{
	background-image:url(home.jpg);
}
	.middle
	{
		margin:190px;
		text-align:left;
		font-size:20px;
		color:beige;
		text-align:justify;
	}
	.logo{

	padding: 0px 0px;
	width:30%;
	height:auto;
}

	
}

</style>

</head>
<title> Gamby General Hospital</title>
<body>
<header>
<div class="header">

<!--
<p> GAMBY GENERAL HOSPITAL <p>&nbsp &nbsp &nbsp &nbsp &nbsp 
-->
</div>

 <div class="top">
 
 <nav>
 <img src="LOG.png" CLASS="logo">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
 <ul> <!--ul-->
 <li><a href="homepage.PHP">home</a></li>
 <li><a href="#">register</a>
   <ul> <!--ul ul-->      
      <li><a href="PATIENTsign.PHP">patient</a></li>
   <li><a href="docsign.PHP">Doctor</a>
       
		  
		  </li>
     
	<li><a href="#">Other Servants</a>
	   <ul><!--ul ul ul--> 
		   <li><a href="receptionsign.PHP">receptionist</a></li>
           <li><a href="pharmacysign.PHP">phamacist</a>
		   <li><a href="labratorysign.PHP">labratorist</a>
	   </ul><!--ul ul ul--> 
		  </li>
	</ul><!--ul ul-->

	</li>
  <li><a href="#">Services</a>
  <ul>
           <li><a href="heart.php">heart condition</a></li>
           <li><a href="pregnancy.php">pregnancy</a></li>
		   <li><a href="skin.php">skin</a></li>
		   <li><a href="kidney.php">kidney dialsis</a></li>
		   
		   
  </ul></li>
  <li><a href="about.php">About Us</a></li>
 <li  type="none"  ><a href="#">Log In</a>
  <ul>
           <li><a href="doclog.php">doctor</a></li>
           <li><a href="patientlog.php">patient</a></li>
		   <li><a href="receptionlog.php">reception</a></li>
		   <li><a href="lablog.php">labratorist</a></li>
		   <li><a href="pharmacylog.php">pharmasist</a></li>
		   <li><a href="adminlogin.php">admin</a></li>

		   
		   
  </ul></li> 
  </ul>
  		   
  
  
</nav>
</div>

</header>
<div class="middle";>
<p>GAMBY HOSPITAL, School of Medicine, College of Health Sciences was established in 1964, and is now <br>the main teaching center for both clinical and preclinical training of most disciplines. It is also an <br>institution where specialized clinical services that are not available in other public or private <br> institutions are rendered to the whole nation.<br>The various<ul><li> departments,</li> <li>faculties and </li> <li>residents</li></ul> under specialty training in the School of Medicine provide patient care in the hospital. In addition, <br>almost all regional and federal hospitals in Addis Ababa are affiliated to </br>the School of Medicine as clinical services and training sites.
 </p>
 </div>
<footer>
<h2>our interesting facts</h2><BR>
<P></P>
<a href="homepage.PHP"><h3>join us today</h3></a>
<br>
<h4 style="float:left;" style="font-size:20px;">
contact us<br>
Addres:BahirDar,kebele 08<br>
call Gamby :058 123464<br>
Emergencies- Appointmnets-Ambulances <br>
Available 24 hours everyday (24/7)<br>
</h4>
<h3>
Over 100 Specialised Doctors<br>
modernised equipments<br>
2402 total Graduates <br>
2660 facebook followers
</h3>

<p>GAMBY GENERAL HOSPITAL <BR>SINCE 1998</p>

</footer>

</body>
</html>